// Code generated by Kitex v0.8.0. DO NOT EDIT.
package stockservice

import (
	server "github.com/cloudwego/kitex/server"
	stock "mykitex/kitex_gen/example/shop/stock"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler stock.StockService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
