// Code generated by Kitex v0.8.0. DO NOT EDIT.

package stockservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	stock "mykitex/kitex_gen/example/shop/stock"
)

func serviceInfo() *kitex.ServiceInfo {
	return stockServiceServiceInfo
}

var stockServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "StockService"
	handlerType := (*stock.StockService)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetItemStock": kitex.NewMethodInfo(getItemStockHandler, newGetItemStockArgs, newGetItemStockResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "item",
		"ServiceFilePath": ``,
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.8.0",
		Extra:           extra,
	}
	return svcInfo
}

func getItemStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(stock.GetItemStockReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(stock.StockService).GetItemStock(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *GetItemStockArgs:
		success, err := handler.(stock.StockService).GetItemStock(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetItemStockResult)
		realResult.Success = success
	}
	return nil
}
func newGetItemStockArgs() interface{} {
	return &GetItemStockArgs{}
}

func newGetItemStockResult() interface{} {
	return &GetItemStockResult{}
}

type GetItemStockArgs struct {
	Req *stock.GetItemStockReq
}

func (p *GetItemStockArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(stock.GetItemStockReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetItemStockArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetItemStockArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetItemStockArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetItemStockArgs) Unmarshal(in []byte) error {
	msg := new(stock.GetItemStockReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetItemStockArgs_Req_DEFAULT *stock.GetItemStockReq

func (p *GetItemStockArgs) GetReq() *stock.GetItemStockReq {
	if !p.IsSetReq() {
		return GetItemStockArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetItemStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetItemStockArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetItemStockResult struct {
	Success *stock.GetItemStockResp
}

var GetItemStockResult_Success_DEFAULT *stock.GetItemStockResp

func (p *GetItemStockResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(stock.GetItemStockResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetItemStockResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetItemStockResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetItemStockResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetItemStockResult) Unmarshal(in []byte) error {
	msg := new(stock.GetItemStockResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetItemStockResult) GetSuccess() *stock.GetItemStockResp {
	if !p.IsSetSuccess() {
		return GetItemStockResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetItemStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*stock.GetItemStockResp)
}

func (p *GetItemStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetItemStockResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetItemStock(ctx context.Context, Req *stock.GetItemStockReq) (r *stock.GetItemStockResp, err error) {
	var _args GetItemStockArgs
	_args.Req = Req
	var _result GetItemStockResult
	if err = p.c.Call(ctx, "GetItemStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
